import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Trip, TripItem } from '@/types';

interface ExportOptions {
  includeNotes?: boolean;
  includeAddress?: boolean;
  includeTime?: boolean;
}

export async function exportTripToPDF(trip: Trip, options: ExportOptions = {}) {
  const {
    includeNotes = true,
    includeAddress = true,
    includeTime = true,
  } = options;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Colors
  const primaryColor: [number, number, number] = [79, 70, 229]; // Indigo-600
  const textColor: [number, number, number] = [31, 41, 55]; // Gray-800
  const lightGray: [number, number, number] = [156, 163, 175]; // Gray-400

  let yPos = 20;

  // Header
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 40, 'F');

  // Trip name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(trip.name, 20, 25);

  // Destination and dates
  if (trip.destination || trip.startDate) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const subText = [
      trip.destination,
      formatDateRange(trip.startDate, trip.endDate),
    ].filter(Boolean).join(' | ');
    doc.text(subText, 20, 34);
  }

  yPos = 50;

  // Description
  if (trip.description) {
    doc.setTextColor(...textColor);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    const descLines = doc.splitTextToSize(trip.description, pageWidth - 40);
    doc.text(descLines, 20, yPos);
    yPos += descLines.length * 5 + 10;
  }

  // Group items by day
  const itemsByDay = trip.items.reduce((acc, item) => {
    if (!acc[item.day]) acc[item.day] = [];
    acc[item.day].push(item);
    acc[item.day].sort((a, b) => a.order - b.order);
    return acc;
  }, {} as Record<number, TripItem[]>);

  const days = Object.keys(itemsByDay).map(Number).sort((a, b) => a - b);

  // No items message
  if (days.length === 0) {
    doc.setTextColor(...lightGray);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('No places added to this trip yet.', 20, yPos);
    yPos += 20;
  }

  // Render each day
  for (const day of days) {
    const items = itemsByDay[day];

    // Check if we need a new page
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }

    // Day header
    const dayDate = getDayDate(trip.startDate, day);

    doc.setFillColor(243, 244, 246); // Gray-100
    doc.roundedRect(15, yPos - 5, pageWidth - 30, 12, 2, 2, 'F');

    doc.setTextColor(...primaryColor);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`Day ${day}`, 20, yPos + 3);

    if (dayDate) {
      doc.setTextColor(...lightGray);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(dayDate, pageWidth - 20, yPos + 3, { align: 'right' });
    }

    yPos += 15;

    // Items table
    const tableData = items.map((item, index) => {
      const row: string[] = [`${index + 1}.`, item.place.name];

      if (includeTime && item.startTime) {
        row.push(formatTime(item.startTime, item.endTime));
      } else if (includeTime) {
        row.push('-');
      }

      if (includeAddress) {
        row.push(item.place.address || '-');
      }

      if (includeNotes) {
        row.push(item.notes || '-');
      }

      return row;
    });

    const columns: string[] = ['#', 'Place'];
    if (includeTime) columns.push('Time');
    if (includeAddress) columns.push('Address');
    if (includeNotes) columns.push('Notes');

    autoTable(doc, {
      startY: yPos,
      head: [columns],
      body: tableData,
      theme: 'striped',
      headStyles: {
        fillColor: primaryColor,
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9,
      },
      bodyStyles: {
        fontSize: 9,
        textColor: textColor,
      },
      columnStyles: {
        0: { cellWidth: 10 },
        1: { cellWidth: 'auto', fontStyle: 'bold' },
        ...(includeTime ? { 2: { cellWidth: 25 } } : {}),
        ...(includeAddress ? { [includeTime ? 3 : 2]: { cellWidth: 50 } } : {}),
        ...(includeNotes ? { [columns.length - 1]: { cellWidth: 40 } } : {}),
      },
      margin: { left: 15, right: 15 },
      didDrawPage: () => {
        // Footer on each page
        doc.setFontSize(8);
        doc.setTextColor(...lightGray);
        doc.text(
          `Generated by Travel Copilot | Powered by YourGPT Copilot SDK | ${new Date().toLocaleDateString()}`,
          pageWidth / 2,
          doc.internal.pageSize.getHeight() - 10,
          { align: 'center' }
        );
      },
    });

    // Get the Y position after the table
    yPos = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;
  }

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...lightGray);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - 20,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'right' }
    );
  }

  // Generate filename
  const fileName = `${trip.name.toLowerCase().replace(/\s+/g, '-')}-itinerary.pdf`;

  // Save the PDF
  doc.save(fileName);

  return fileName;
}

function formatDateRange(startDate?: string, endDate?: string): string | null {
  if (!startDate) return null;
  const start = new Date(startDate).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
  if (!endDate) return start;
  const end = new Date(endDate).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
  return `${start} - ${end}`;
}

function getDayDate(startDate: string | undefined, day: number): string | null {
  if (!startDate) return null;
  const date = new Date(startDate);
  date.setDate(date.getDate() + day - 1);
  return date.toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'short',
    day: 'numeric',
  });
}

function formatTime(startTime?: string, endTime?: string): string {
  if (!startTime) return '-';

  const formatSingleTime = (time: string) => {
    try {
      const [hours, minutes] = time.split(':');
      const h = parseInt(hours, 10);
      const ampm = h >= 12 ? 'PM' : 'AM';
      const hour12 = h % 12 || 12;
      return `${hour12}:${minutes} ${ampm}`;
    } catch {
      return time;
    }
  };

  const start = formatSingleTime(startTime);
  if (!endTime) return start;
  const end = formatSingleTime(endTime);
  return `${start} - ${end}`;
}
